Style/FrozenStringLiteralComment:
  Enabled: false
Metrics/LineLength:
  Enabled: false
Style/StringLiterals:
  Enabled: false
Style/Documentation:
  Enabled: false
Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: false
Style/ExpandPathArguments:
  Enabled: false
Style/MixinUsage:
  Enabled: false
Style/StderrPuts:
  Enabled: false
Style/SymbolArray:
  Enabled: false
Bundler/OrderedGems:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
