name: Rubocop

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: [ '2.5.x', '2.6.x' ]
    name: Ruby ${{ matrix.ruby }} sample
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Set up Ruby version
        uses: actions/setup-ruby@master
        with:
          ruby-version: ${{ matrix.ruby }}
      - run: ruby -v
      - name: apt-get
        run: |
          sudo apt-get update
          sudo apt-get install libsqlite3-dev
      - name: Set up bundler
        run: gem install bundler

      - name: Cache gems
        uses: actions/cache@preview
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gem-

      - name: bundle install
        run: bundle install --path vendor/bundle
      - name: Rubocop checks
        run: bundle exec rubocop
      - name: Rubocop stats
        if: failure()
        run: |
          mkdir -p rubocop_result
          bundle exec rubocop -f o > rubocop_result/rubocop_offenses.txt
          bundle exec rubocop -f h -o rubocop_result/rubocop.html
      - name: RSpec
        run: bundle exec rspec
      - name: Upload artifact
        uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: rubocop-result
          path: rubocop_result
