on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      # To use this repository's private action, you must check out the repository
      - name: Checkout
        uses: actions/checkout@v1
      - name: Hello world action step
        uses: ./private_hw_action/ # Uses an action in the root directory
        id: hello
        with:
          who-to-greet: 'Private Mona the Octocat with ncc'
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
      - name: Hello world docker action step
        id: hello
        uses: kyamaguchi/hello-world-docker-action@master
        with:
          who-to-greet: 'Mona the Docker'
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
