on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Hello world action step
      id: hello
      uses: kyamaguchi/hello-world-javascript-action@v1.0
      with:
        who-to-greet: 'Mona the Octocat'
    # Use the output from the `hello` step
    - name: Get the output time
      run: echo "The time was ${{ steps.hello.outputs.time }}"
    - name: Check pwd
      run: pwd
    - name: Check ls
      run: ls -al
    - name: Check root
      run: ls -al /
    - name: Check bin
      run: ls -al /bin
    - name: Check many dirs
      run: ls -al /data /dev /etc /home /lib /srv
    - name: Check work dir
      run: ls -al /home/runner/work /home/runner/work/gh_actions_ex
    - name: Find git
      run: which git
